### ISSUE TITLE
Generic Scale-to-Zero Support

### ISSUE THREAD

**Issue by hardikdr** [gardener/autoscaler#27]
## What would you like to be added

1. Allow scale from zero across all providers support by [MCM](https://github.com/gardener/machine-controller-manager).
2. Configure the upcoming resources (CPU/Memory) while scaling from zero for a worker pool in a dynamic manner.
3. ~Allow for CA to be aware of enhanced memory/CPU done by `memory-one-suse-CHost`~

## Why is this needed

- Currently, this is logic for fetching instance details is harder coded for AWS and Azure [as seen here](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L667-L686).
- The instance attributes are fetched from a [static file today like this one](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go). 

## Decisions made

- To support case (3) of requirement, we had several rounds of internal discussions where possible hacks were discussed. However, this leads to a lot of custom hacks to incorporate this and wouldn't be the right way.
- ~Hence it was decided to go the combine this feature with the generic scale from zero feature to handle this scenario as well.~
- Now its decided to seperate the solution of case (3) from generic-scale-from-zero story . Check the new solution [here](https://github.com/gardener/autoscaler/issues/103)

## Next Steps

- Evaluating the implementation details

## High-Level Design

The following is a rough design to implement this feature. 

From MCM/Autoscaler integration.
- The details required to fill in the resources per node will be filled up at the [machineClass level](https://github.com/gardener/machine-controller-manager/blob/master/pkg/apis/machine/types.go#L1203-L1217) with either spec fields or annotation with a field called `nodeTemplate`.
- This field will consist of the following sub fields - `MachineType`, `CPU`, `Memory`, `GPU`, `Zone`, and any other value the CA expects for scale-up. 
- During scale-up, the CA would use these resource values passed on the `machineClass` to generate the dummy node object to simulate the new node. However, if no values are passed on the machineClass it would fall back to the existing static values (for only currently supported providers - AWS, Azure). 

From Gardener (Any higher controller point of view),
- The Worker resource spec would contain additional field `nodeTemplate` with the following subfields - CPU, GPU, Memory.
- These values will default from the cloud profile by gardenlet.
- Gardener extension providers will then pass this `nodeTemplate` field to `machineClass` with addition of instanceType, region and zone.

Approaching this problem solves ~3 different issues~ 2 different issues
- [Generic scale from zero support for all providers](https://github.com/gardener/autoscaler/issues/27)
- [Build machine type details dynamically](https://github.com/gardener/autoscaler/issues/88)
- ~Allow customers to configure specific instance type resource overrides - In case any form of virtualization/emulation enhances default resource values like [this issue](https://github.com/gardener/autoscaler/issues/95).~

## Open Questions

- [x] Should we use existing annotation with a predefined key or introduce a new API field in the spec in machineClass
    - Its decided that [APIs are introduced](https://github.com/gardener/machine-controller-manager/blob/cc66a5130b21528e8b3c0ef3301de318efa5807c/pkg/apis/machine/types.go#L1209-L1211)
- [x] Should we use existing annotation with a predefined key or introduce a new API field in the spec in Gardener and Extension APIs 
    - Its decided that APIs are introduced
- [x] Who should Default of values when not set? Gardener (or) extension providers? 
   - Gardenlet

## Task List

The assumption to the task list above is that we go the new API field way and not the annotation way. If we go the annotation way, the steps below would be similar but would be simplified. 

### Changes at MCM

- [x] #98

### Changes at Cluster Autoscaler

In the provider MCM code, the following changes have to be made
- [x] Update the CA to the latest upstream version
- [x] Revendor the MCM with the above new API version
- [x] Update [these methods](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L751-L804) to default from the new field however it falls back to the existing way of picking from static file (for AWS and Azure).

### Changes at Gardener

- [x] Introduce a new extension API field `*nodeTemplate` in `.WorkerPool` section [here](https://github.com/gardener/gardener/blob/master/pkg/apis/extensions/v1alpha1/types_worker.go#L98). 
- [x] This has to be initialized from CloudProfile by gardenlet
- [ ] Release the gardener/gardener changes above

### Changes at Gardener Extension Providers

- [ ] Use the above API field values to set the values for the new MachineClass field in the machineClass chart like [this one](https://github.com/gardener/gardener-extension-provider-aws/blob/master/charts/internal/machineclass/templates/machineclass.yaml).
  - [ ] Alicloud
  - [ ] AWS
  - [ ] Azure
  - [ ] GCP
  - [ ] Openstack
  - [ ] VMWare
  - [ ] Others

**Comment by rewiko** [comment]
I think the second option makes sense to me, defining the instance types/Zone/OS/Arch on the machine class would allow autoscaler with mcm as provider to be agnostic of any others provider.

**Comment by enxebre** [comment]
how about providers that can't be conveyed in a static instanceTypes variable but rather need to fetch values dynamically, e.g vsphere, openstack., libvirt, baremetal...
Wouldn't it be reasonable to rather let each provider class controller to the provider specific logic to fetch values from a type (dynamically or statically, let it be a provider choice), and let the class expose them via status/annotations, so we can keep provider neutrality in the autoscaler mcm-provider by using a dynamic client to fetch the class and retrieve the values from the known provider agnostic status/annotations
https://github.com/gardener/autoscaler/pull/26#discussion_r368692773

**Comment by prashanth26** [comment]
We already have support for AWS and Azure, the generic support that works for all providers is to be worked upon.

**Comment by prashanth26** [comment]
The following is the rough design to implement this feature. 

From MCM/Autoscaler integration.
- The details required to fill in the resources per node will be filled up at the [machineClass level](https://github.com/gardener/machine-controller-manager/blob/master/pkg/apis/machine/types.go#L1203-L1217) with either spec fields or annotation.
- The spec/annotations will consist of the following fields - `MachineType`, `CPU`, `Memory`, `GPU`, `Zone` and any other value the CA expects for scale-up. 
- During scale-up, the CA would use these resource values passed on the `machineClass` to generate the dummy node object to simulate the new node. However, if no values are passed on the machineClass it would fall back to the existing values. 


From Gardener (Any higher controller point of view),
- The shoot spec would contain additional fields (CPU, GPU, Memory) in the [worker section](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L29-L45) that would let you override the default resource utilizations.
- If not specified, these values will default from the cloud profile and work as it is today. 

Approaching this problem solves 3 different issues
- [Generic scale from zero support for all providers](https://github.com/gardener/autoscaler/issues/27)
- [Build machine type details dynamically](https://github.com/gardener/autoscaler/issues/88)
- Allow customers to configure specific instance type resource overrides - In case any form of virtualization/emulation to enhance default resource values.

**Comment by amshuman-kr** [comment]
Thanks for the rough design @prashanth26! Looks good. A small suggestion, let's have the word `expectedNodeDetails` (or something more readable 😅) in the  the additional field names (either as additional nesting level or part of the name) or annotation keys.

**Comment by prashanth26** [comment]
Sure @amshuman-kr. Let's keep it that way.

**Comment by prashanth26** [comment]
## What would you like to be added

1. Allow scale from zero across all providers support by [MCM](https://github.com/gardener/machine-controller-manager).
2. Configure the upcoming resources (CPU/Memory) while scaling from zero for a worker pool in a dynamic manner.
3. Allow customers to configure specific instance type resource overrides - In case any form of virtualization/emulation to enhances default resource values.

## Why is this needed

- Currently, this is logic for fetching instance details is harder coded for AWS and Azure [as seen here](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L667-L686).
- The instance attributes are fetched from a [static file today like this one](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go). 
- In cases of virtualization/emulation scenarios where some software/hardware mechanisms are able to simulate/generate a higher resource allocation, such machines should be made aware of the cluster autoscaler. 

## Decisions made

- To support case (3) of requirement, we had several rounds of internal discussions where possible hacks were discussed. However, this leads to a lot of custom hacks to incorporate this and wouldn't be the right way.
- Hence it was decided to go the combine this feature with the generic scale from zero feature to handle this scenario as well.

## Next Steps

- We are currently working on the design and possible implementations and discussing the options internally. 

## High-Level Design (Tentative, is under refinement with internal discussions)

The following is the rough design to implement this feature. 

From MCM/Autoscaler integration.
- The details required to fill in the resources per node will be filled up at the [machineClass level](https://github.com/gardener/machine-controller-manager/blob/master/pkg/apis/machine/types.go#L1203-L1217) with either spec fields or annotation with a field called `expectedNodeDetails`.
- The spec/annotations will consist of the following fields - `MachineType`, `CPU`, `Memory`, `GPU`, `Zone`, and any other value the CA expects for scale-up. 
- During scale-up, the CA would use these resource values passed on the `machineClass` to generate the dummy node object to simulate the new node. However, if no values are passed on the machineClass it would fall back to the existing values. 

From Gardener (Any higher controller point of view),
- The shoot spec would contain additional fields (CPU, GPU, Memory) in the [worker section](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L29-L45) that would let you override the default resource utilizations.
- If not specified, these values will default from the cloud profile and work as it is today. 

Approaching this problem solves 3 different issues
- [Generic scale from zero support for all providers](https://github.com/gardener/autoscaler/issues/27)
- [Build machine type details dynamically](https://github.com/gardener/autoscaler/issues/88)
- Allow customers to configure specific instance type resource overrides - In case any form of virtualization/emulation to enhances default resource values.

**Comment by rfranzke** [comment]
> The shoot spec would contain additional field expectedNodeDetails with the following subfields - CPU, GPU, Memory in the worker section that would let you override the default resource utilizations.

> If not specified, these values will default from the cloud profile and work as it is today.

Why is this needed? With Gardener, only machine types specified in the `CloudProfile` can be used. Why would we allow overriding these machine type specifics? Why can't we just use the information from the `CloudProfile`s?

**Comment by rfranzke** [comment]
>  Introduce a new extension API field *expectedNodeDetails in .WorkerPool section here.

Alternatively, the `Worker` extension could again just read the information from the `CloudProfile`. OTOH, Gardener could just populate the information in the `Worker` object (I would not call the field `expectedNodeDetails` but maybe `machineTypeDetails` or `machineTypeInformation` or similar). Then the `Worker` extension does not need to find the information itself (especially as this would be needed to be implemented for all providers).

**Comment by AxiomSamarth** [comment]
> > The shoot spec would contain additional field expectedNodeDetails with the following subfields - CPU, GPU, Memory in the worker section that would let you override the default resource utilizations.
> 
> > If not specified, these values will default from the cloud profile and work as it is today.
> 
> Why is this needed? With Gardener, only machine types specified in the `CloudProfile` can be used. Why would we allow overriding these machine type specifics? Why can't we just use the information from the `CloudProfile`s?

@rfranzke Here is one rationale behind the proposal. 

With OS's like ScaleMP where the machine resources of exisiting machine types are scaled up during runtime, `CloudProfile` will not be able to capture those new specs. Which is why, CA may fail to scale the machines (from zero especially) as it will not be able to generate the required node template. If CA has to work seamlessly for such scenarios then it needs to understand the node specs dynamically from the `MachineClass` and not from the predefined catalogue of machines.

@prashanth26 Can provide further insights.

**Comment by rfranzke** [comment]
OK, got it, thanks. My question would be: If I have a worker pool with ScaleMP and multiple machines, does this "where the machine resources of exisiting machine types are scaled up during runtime" behave equally for all such machines? Or is it individual per machine?

**Comment by AxiomSamarth** [comment]
Yes, the behaviour would be same for all such machines of a (exemplar) ScaleMP worker pool (as I understand that all machines in a Gardener worker pool are of same type and here in this example, they would be the ones with MemoryOne CHost OS).

**Comment by prashanth26** [comment]
> > The shoot spec would contain additional field expectedNodeDetails with the following subfields - CPU, GPU, Memory in the worker section that would let you override the default resource utilizations.
> 
> > If not specified, these values will default from the cloud profile and work as it is today.
> 
> Why is this needed? With Gardener, only machine types specified in the `CloudProfile` can be used. Why would we allow overriding these machine type specifics? Why can't we just use the information from the `CloudProfile`s?

I think @AxiomSamarth pretty much answered this. However for more details please refer this issue - https://github.com/gardener/autoscaler/issues/95. 

> OK, got it, thanks. My question would be: If I have a worker pool with ScaleMP and multiple machines, does this "where the machine resources of exisiting machine types are scaled up during runtime" behave equally for all such machines? Or is it individual per machine?

Great question :) I would expect ScaleMP to behave similarly in all such machines (at least belonging to a worker pool).  But however, you are right, I think ScaleMP can create the same machines with different effective resources sizes. Would probably invite the ScaleMP colleagues to answer this.

**Comment by vlerenc** [comment]
We have the "funny" problem here, that the node capacity (as in K8s node resource) varies with the OS.

Therefore, I guess, I would go with `.spec.provider.workers[].machine.capacity.(cpu|gpu|memory)`. I am somewhat unsure whether there are also models that "expand/shrink" the number of CPUs? And, maybe we took already a wrong turn with GPUs, because e.g. on GCP they can be attached and aren't necessarily a property of the machine type. So maybe, we should only allow `.spec.provider.workers[].machine.capacity.memory` and add more fields only when they make sense?

In any case, `.spec.provider.workers[].machine.capacity` would override whatever is defined in the cloud profiles for that particular `.spec.provider.workers[].machine.type`. And yes, either the default from the cloud profile or the overridden memory value should be probably put into the machine class and should then be read only from there (by CA and co.).

**Comment by rfranzke** [comment]
I'm wondering whether this is something that is OS-specific, i.e., whether it better fits into the provider configuration of the machine image instead of the core API. What are your thoughts?

Instead of `.spec.provider.workers[].machine.capacity`, it could look like this:

```yaml
spec:
  provider:
    workers:
    - name: foo
      machine:
        type: m4.xlarge
        image:
          name: memoryone-chost
          providerConfig:
            apiVersion: memoryone-chost.os.extensions.gardener.cloud/v1alpha1
            kind: OperatingSystemConfiguration
            memoryTopology: "3"
            systemMemory: "7x"
            capacity:
              memory: 1234Mi
      minimum: 2
      maximum: 100
      ...
```

FYI: The `memoryone-chost.os.extensions.gardener.cloud/v1alpha1.OperatingSystemConfiguration` API and the `memoryTopology` and `systemMemory` fields already exist today.

**Comment by himanshu-kun** [comment]
I agree with you @rfranzke , that we can add a field `capacity` in the `memoryone-chost.os.extensions.gardener.cloud/v1alpha1.OperatingSystemConfiguration` API and can solve the problem for scaleMP colleagues this way.
But this would still leave the generic scaleFromZero problem unsolved, which we have to come to solve one day. With [this](https://github.com/gardener/autoscaler/issues/27#issuecomment-899998390) approach though(yes there will be a changes in each extension provider) we are hitting three targets with one arrow, is what I think. Comments welcomed !

**Comment by rfranzke** [comment]
OK, understood. Then let's drop the proposal about enhancing the `memoryone-chost` API again and instead

- add a `capacity` field to the `core.gardener.cloud/v1beta1.Machine` structure as suggested above.
- add a `machineCapacity` field to the `extensions.gardener.cloud/v1alpha1.WorkerPool` structure that contains the fields needed for autoscaler (CPU, memory, whatever) - this can be set by gardenlet when the `Worker` resource is created (based on the `CloudProfile` and potential overrides in the worker pool spec in the `Shoot`, hence, no adaptations in the extensions required, right?).

WDYT?

**Comment by AxiomSamarth** [comment]
> OK, understood. Then let's drop the proposal about enhancing the `memoryone-chost` API again and instead
> 
> * add a `capacity` field to the `core.gardener.cloud/v1beta1.Machine` structure as suggested above.
> * add a `machineCapacity` field to the `extensions.gardener.cloud/v1alpha1.WorkerPool` structure that contains the fields needed for autoscaler (CPU, memory, whatever) - this can be set by gardenlet when the `Worker` resource is created (based on the `CloudProfile` and potential overrides in the worker pool spec in the `Shoot`, hence, no adaptations in the extensions required, right?).
> 
> WDYT?

I like this one.

**Comment by himanshu-kun** [comment]
> OK, understood. Then let's drop the proposal about enhancing the `memoryone-chost` API again and instead
> 
> * add a `capacity` field to the `core.gardener.cloud/v1beta1.Machine` structure as suggested above.
> * add a `machineCapacity` field to the `extensions.gardener.cloud/v1alpha1.WorkerPool` structure that contains the fields needed for autoscaler (CPU, memory, whatever) - this can be set by gardenlet when the `Worker` resource is created (based on the `CloudProfile` and potential overrides in the worker pool spec in the `Shoot`, hence, no adaptations in the extensions required, right?).
> 
> WDYT?

Yes this looks good, but doesn't it just carries down the CPU, memory info till the worker resource level onlyi.e. till the gardener level only. Because afterall we want these info to reach the machineClass and since we are introducing a new field in `extensions.gardener.cloud/v1alpha1.WorkerPool` , we'll have to add changes in extension provider code to pick values from this field and add them to machineClass. 
One place we are thinking of adding them to the machineClass is in the labels like [here](https://github.com/gardener/gardener-extension-provider-aws/blob/2ea34f6fe7c199b07e9f39bd8e5f40024382addb/pkg/controller/worker/machines.go#L204)
or we are thinking of adding new field to the providerSpec of machineClass in which case we'll have to assign values [here](https://github.com/gardener/gardener-extension-provider-aws/blob/2ea34f6fe7c199b07e9f39bd8e5f40024382addb/pkg/controller/worker/machines.go#L147-L174)
Though the labels way looks easier , as we won't have to change the providerSpec of different providers in this way.
Comments welcomed!

**Comment by rfranzke** [comment]
Sure, makes sense, thanks @himanshu-kun. 

> One place we are thinking of adding them to the machineClass is in the labels like here
> or we are thinking of adding new field to the providerSpec of machineClass in which case we'll have to assign values here

Using the `providerSpec` doesn't seem reasonable since this information is in no way provider-specific. Labels could be used, but what speaks against a regular field in the `MachineClass` resource?

**Comment by sunir1** [comment]
> > > The shoot spec would contain additional field expectedNodeDetails with the following subfields - CPU, GPU, Memory in the worker section that would let you override the default resource utilizations.
> > 
> > 
> > > If not specified, these values will default from the cloud profile and work as it is today.
> > 
> > 
> > Why is this needed? With Gardener, only machine types specified in the `CloudProfile` can be used. Why would we allow overriding these machine type specifics? Why can't we just use the information from the `CloudProfile`s?
> 
> I think @AxiomSamarth pretty much answered this. However for more details please refer this issue - #95.
> 
> > OK, got it, thanks. My question would be: If I have a worker pool with ScaleMP and multiple machines, does this "where the machine resources of exisiting machine types are scaled up during runtime" behave equally for all such machines? Or is it individual per machine?
> 
> Great question :) I would expect ScaleMP to behave similarly in all such machines (at least belonging to a worker pool). But however, you are right, I think ScaleMP can create the same machines with different effective resources sizes. Would probably invite the ScaleMP colleagues to answer this.

Indeed with vSMP MemoryONE (This is the correct product name, not 'ScaleMP'), we are able to define different WorkerGroups, each with different DRAM to overall system memory ratio (even if they are using the same raw hyper-scaler instance type).

For example:
Taking m5d.16xlarge with 256GB of DRAM, and creating a VM with 1TB
Or taking m5d.15xlage, with 2TB of system memory.

However, each of them would be a different WorkerGroup, and as such, within a single WorkerGroup, all 'machines' would have the same amount of memory (or CPU, GPU).

**Comment by himanshu-kun** [comment]
Yes @rfranzke I think a MachineClass regular field is a good idea as well. Thanks, I had missed that.

**Comment by prashanth26** [comment]
Apologies for the delayed response. 

I agree with adding this as an API field at the levels mentioned. However, W.R.T to which fields are to be kept at the machineClass level, we would at least need the following fields (which can be generated from the cloud profile) as these are fields expected at the cluster autoscaler. Refer 
1. https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L724-L730
2. https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L765-L771

```
expectedNodeDetails:
  machineType:
  memory:
  cpu: 
  gpu: 
  region:
  zone: 
```
These fields are today taken from the static file or some hacks. We will need to generate this at the extension level. However yes, the overriding we can just keep it to memory for now at the Gardener APIs level?

Also changing the field name to `expectedNodeDetails` as this contains more details than just `capacity`. WDYT?

**Comment by AxiomSamarth** [comment]
We may also have to consider a scenario where the CA is expected to scale up from zero based on some extended resource limits & requests apart from CPU, Memory, GPU, Zone.
